class Manufacturer {
  String? manufacturer;
  List<String>? model;

  Manufacturer({this.manufacturer, this.model});

  Manufacturer.fromJson(Map<String, dynamic> json) {
    manufacturer = json['manufacturer'];
    model = json['model'].cast<String>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['manufacturer'] = this.manufacturer;
    data['model'] = this.model;
    return data;
  }

  @override
  String toString() {
    return manufacturer ?? 'n/a';
  }
}

final ids = Set();

var manufacturers = [
  {
    "manufacturer": "Ford",
    "model": [
      "Model T",
      "Thunderbird",
      "E-Series",
      "Mustang",
      "Galaxie",
      "Fairlane",
      "Falcon",
      "Country",
      "Torino",
      "Bronco II",
      "Laser",
      "EXP",
      "Ranger",
      "Escort",
      "Tempo",
      "LTD",
      "F250",
      "F150",
      "E250",
      "LTD Crown Victoria",
      "Bronco",
      "E150",
      "F-Series",
      "Taurus",
      "Aerostar",
      "Courier",
      "Festiva",
      "Probe",
      "Explorer",
      "Crown Victoria",
      "Club Wagon",
      "Econoline E150",
      "Econoline E250",
      "Econoline E350",
      "F350",
      "Lightning",
      "Aspire",
      "Windstar",
      "Contour",
      "Expedition",
      "Th!nk",
      "Explorer Sport Trac",
      "Escape",
      "Excursion",
      "Explorer Sport",
      "Focus",
      "Fiesta",
      "ZX2",
      "Escort ZX2",
      "Freestar",
      "E350",
      "GT",
      "Freestyle",
      "Five Hundred",
      "F-250 Super Duty",
      "F-350 Super Duty",
      "E-350 Super Duty",
      "E-350 Super Duty Van",
      "Fusion",
      "F-Series Super Duty",
      "GT500",
      "Edge",
      "Expedition EL",
      "Taurus X",
      "F450",
      "Flex",
      "Transit Connect",
      "C-MAX Hybrid",
      "Focus ST"
    ]
  },
  {
    "manufacturer": "Chrysler",
    "model": [
      "Imperial",
      "Fifth Ave",
      "LeBaron",
      "New Yorker",
      "Town & Country",
      "Concorde",
      "LHS",
      "Cirrus",
      "Sebring",
      "300M",
      "300",
      "Grand Voyager",
      "Voyager",
      "PT Cruiser",
      "Prowler",
      "Crossfire",
      "Pacifica",
      "300C",
      "Crossfire Roadster",
      "Aspen",
      "200"
    ]
  },
  {
    "manufacturer": "Citroën",
    "model": ["2CV", "SM", "CX"]
  },
  {
    "manufacturer": "Hillman",
    "model": ["Minx Magnificent"]
  },
  {
    "manufacturer": "Chevrolet",
    "model": [
      "Corvette",
      "Corvair",
      "Corvair 500",
      "Camaro",
      "Bel Air",
      "Vega",
      "Monte Carlo",
      "Monza",
      "Caprice",
      "LUV",
      "Citation",
      "1500",
      "2500",
      "3500",
      "APV",
      "Astro",
      "Beretta",
      "Blazer",
      "Cavalier",
      "Corsica",
      "G-Series G10",
      "G-Series G20",
      "G-Series G30",
      "Lumina",
      "Lumina APV",
      "S10 Blazer",
      "S10",
      "Sportvan G10",
      "Sportvan G20",
      "Sportvan G30",
      "Suburban 1500",
      "Suburban 2500",
      "Caprice Classic",
      "Impala SS",
      "Impala",
      "K5 Blazer",
      "Tahoe",
      "Express 1500",
      "Express 2500",
      "Express 3500",
      "G-Series 1500",
      "G-Series 2500",
      "Malibu",
      "G-Series 3500",
      "Venture",
      "Metro",
      "Prizm",
      "Tracker",
      "Silverado",
      "Silverado 1500",
      "Silverado 2500",
      "Silverado 3500",
      "Avalanche",
      "Trailblazer",
      "Avalanche 1500",
      "Avalanche 2500",
      "SSR",
      "Aveo",
      "Classic",
      "Colorado",
      "Cobalt",
      "Equinox",
      "Uplander",
      "Suburban",
      "Silverado 3500HD",
      "HHR Panel",
      "Malibu Maxx",
      "HHR",
      "Silverado Hybrid",
      "Express",
      "Cobalt SS",
      "Traverse",
      "Volt",
      "Cruze",
      "Sonic"
    ]
  },
  {
    "manufacturer": "Cadillac",
    "model": [
      "Fleetwood",
      "Seville",
      "Allante",
      "Brougham",
      "DeVille",
      "Eldorado",
      "Sixty Special",
      "Catera",
      "Escalade",
      "Escalade EXT",
      "CTS",
      "Escalade ESV",
      "SRX",
      "XLR",
      "STS",
      "DTS",
      "XLR-V",
      "CTS-V",
      "STS-V"
    ]
  },
  {
    "manufacturer": "BMW",
    "model": [
      "600",
      "6 Series",
      "3 Series",
      "5 Series",
      "7 Series",
      "8 Series",
      "M5",
      "M3",
      "Z3",
      "X5",
      "M",
      "Z8",
      "525",
      "530",
      "745",
      "760",
      "Z4",
      "325",
      "545",
      "645",
      "X3",
      "330",
      "550",
      "650",
      "750",
      "M6",
      "M Roadster",
      "Z4 M",
      "Alpina B7",
      "1 Series",
      "X6",
      "Z4 M Roadster",
      "X5 M",
      "X6 M"
    ]
  },
  {
    "manufacturer": "Austin",
    "model": ["Mini", "Mini Cooper", "Mini Cooper S"]
  },
  {
    "manufacturer": "Fillmore",
    "model": ["Fillmore"]
  },
  {
    "manufacturer": "Fairthorpe",
    "model": ["Rockette"]
  },
  {
    "manufacturer": "Studebaker",
    "model": ["Avanti"]
  },
  {
    "manufacturer": "Pontiac",
    "model": [
      "Tempest",
      "Grand Prix",
      "GTO",
      "LeMans",
      "Bonneville",
      "Firebird",
      "6000",
      "Sunbird",
      "1000",
      "Parisienne",
      "Fiero",
      "Firefly",
      "Grand Am",
      "Safari",
      "Gemini",
      "Firebird Trans Am",
      "Chevette",
      "Turbo Firefly",
      "Trans Sport",
      "Grand Prix Turbo",
      "Firebird Formula",
      "Sunfire",
      "Montana",
      "Aztek",
      "Vibe",
      "G6",
      "Daewoo Kalos",
      "Monterey",
      "Montana SV6",
      "Torrent",
      "Solstice",
      "G5",
      "G8",
      "G3"
    ]
  },
  {
    "manufacturer": "Buick",
    "model": [
      "Special",
      "Riviera",
      "Electra",
      "Century",
      "Skyhawk",
      "Somerset",
      "LeSabre",
      "Regal",
      "Skylark",
      "Reatta",
      "Estate",
      "Coachbuilder",
      "Park Avenue",
      "Roadmaster",
      "Hearse",
      "Rendezvous",
      "Rainier",
      "LaCrosse",
      "Terraza",
      "Lucerne",
      "Enclave",
      "Verano"
    ]
  },
  {
    "manufacturer": "Rambler",
    "model": ["Classic"]
  },
  {
    "manufacturer": "Plymouth",
    "model": [
      "Fury",
      "Roadrunner",
      "Volare",
      "Horizon",
      "Reliant",
      "Voyager",
      "Laser",
      "Acclaim",
      "Colt",
      "Colt Vista",
      "Grand Voyager",
      "Sundance",
      "Neon",
      "Breeze",
      "Prowler"
    ]
  },
  {
    "manufacturer": "Volkswagen",
    "model": [
      "Beetle",
      "Golf",
      "Jetta",
      "Vanagon",
      "Scirocco",
      "Quantum",
      "GTI",
      "Cabriolet",
      "Passat",
      "Type 2",
      "Fox",
      "Corrado",
      "Eurovan",
      "riolet",
      "Golf III",
      "Jetta III",
      "rio",
      "New Beetle",
      "Touareg",
      "R32",
      "Phaeton",
      "Rabbit",
      "Eos",
      "GLI",
      "Touareg 2",
      "CC",
      "Tiguan",
      "Routan"
    ]
  },
  {
    "manufacturer": "Jensen",
    "model": ["Interceptor"]
  },
  {
    "manufacturer": "Oldsmobile",
    "model": [
      "Toronado",
      "88",
      "98",
      "Achieva",
      "Bravada",
      "Ciera",
      "Custom Cruiser",
      "Cutlass Supreme",
      "Silhouette",
      "Cutlass Cruiser",
      "Aurora",
      "Cutlass",
      "LSS",
      "Regency",
      "Intrigue",
      "Alero"
    ]
  },
  {
    "manufacturer": "Mercury",
    "model": [
      "Cougar",
      "Topaz",
      "Grand Marquis",
      "Lynx",
      "Capri",
      "Marquis",
      "Sable",
      "Tracer",
      "Villager",
      "Mystique",
      "Mountaineer",
      "Marauder",
      "Monterey",
      "Montego",
      "Mariner",
      "Milan"
    ]
  },
  {
    "manufacturer": "Shelby",
    "model": ["GT500", "GT350"]
  },
  {
    "manufacturer": "Dodge",
    "model": [
      "Charger",
      "Aspen",
      "Omni",
      "Aries",
      "Daytona",
      "Caravan",
      "Colt",
      "Viper",
      "D150 Club",
      "D150",
      "D250 Club",
      "D250",
      "D350 Club",
      "D350",
      "Dakota Club",
      "Dakota",
      "Dynasty",
      "Grand Caravan",
      "Monaco",
      "Ram 50",
      "Ram Van B150",
      "Ram Van B250",
      "Ram Van B350",
      "Ram Wagon B150",
      "Ram Wagon B250",
      "Ram Wagon B350",
      "Ramcharger",
      "Shadow",
      "Spirit",
      "Stealth",
      "Viper RT/10",
      "Intrepid",
      "Ram",
      "Ram 1500",
      "Ram 2500",
      "Ram 3500",
      "Avenger",
      "Neon",
      "Ram 1500 Club",
      "Ram 2500 Club",
      "Ram 3500 Club",
      "Ram Van 1500",
      "Ram Van 2500",
      "Ram Van 3500",
      "Stratus",
      "Durango",
      "Magnum",
      "Sprinter",
      "Nitro",
      "Caliber",
      "Challenger",
      "Journey"
    ]
  },
  {
    "manufacturer": "Porsche",
    "model": [
      "914",
      "944",
      "911",
      "928",
      "924 S",
      "924",
      "968",
      "Boxster",
      "Cayenne",
      "Carrera GT",
      "Cayman",
      "Panamera"
    ]
  },
  {
    "manufacturer": "Toyota",
    "model": [
      "Celica",
      "MR2",
      "Truck Xtracab SR5",
      "Previa",
      "Camry",
      "4Runner",
      "Corolla",
      "Cressida",
      "Land Cruiser",
      "Paseo",
      "Supra",
      "Tercel",
      "Xtra",
      "T100",
      "Avalon",
      "T100 Xtra",
      "Tacoma",
      "Tacoma Xtra",
      "RAV4",
      "Sienna",
      "Solara",
      "Tundra",
      "Ipsum",
      "Echo",
      "Highlander",
      "Prius",
      "Sequoia",
      "Matrix",
      "Yaris",
      "Camry Solara",
      "Highlander Hybrid",
      "Camry Hybrid",
      "FJ Cruiser",
      "TundraMax",
      "Venza",
      "Prius v",
      "Prius Plug-in Hybrid",
      "Prius c",
      "Prius Plug-in"
    ]
  },
  {
    "manufacturer": "Mercedes-Benz",
    "model": [
      "W123",
      "W126",
      "S-Class",
      "E-Class",
      "W201",
      "SL-Class",
      "190E",
      "300CE",
      "300D",
      "300E",
      "300SD",
      "300SE",
      "300SL",
      "300TE",
      "400E",
      "400SE",
      "500E",
      "500SEL",
      "500SL",
      "600SEL",
      "C-Class",
      "400SEL",
      "500SEC",
      "600SEC",
      "600SL",
      "SLK-Class",
      "M-Class",
      "CL-Class",
      "CLK-Class",
      "G-Class",
      "SLR McLaren",
      "CLS-Class",
      "G55 AMG",
      "SL65 AMG",
      "R-Class",
      "GL-Class",
      "SLK55 AMG",
      "CL65 AMG",
      "Sprinter",
      "GLK-Class",
      "SLS AMG",
      "SLS-Class",
      "Sprinter 2500",
      "Sprinter 3500"
    ]
  },
  {
    "manufacturer": "MG",
    "model": ["MGB"]
  },
  {
    "manufacturer": "Nissan",
    "model": [
      "280ZX",
      "Maxima",
      "Datsun/Nissan Z-car",
      "300ZX",
      "Sentra",
      "240SX",
      "NX",
      "Pathfinder",
      "Stanza",
      "Altima",
      "Quest",
      "200SX",
      "Frontier",
      "Xterra",
      "350Z",
      "Murano",
      "Titan",
      "Pathfinder Armada",
      "Armada",
      "350Z Roadster",
      "Versa",
      "Rogue",
      "Cube",
      "GT-R",
      "370Z",
      "Leaf",
      "JUKE",
      "NV1500",
      "NV2500",
      "NV3500"
    ]
  },
  {
    "manufacturer": "Honda",
    "model": [
      "Civic",
      "Accord",
      "CR-X",
      "Prelude",
      "del Sol",
      "Passport",
      "Odyssey",
      "CR-V",
      "Insight",
      "S2000",
      "Pilot",
      "Element",
      "Civic Si",
      "Civic GX",
      "Ridgeline",
      "Fit",
      "Accord Crosstour",
      "CR-Z",
      "FCX Clarity",
      "Crosstour"
    ]
  },
  {
    "manufacturer": "Renault",
    "model": ["Alliance"]
  },
  {
    "manufacturer": "Mazda",
    "model": [
      "626",
      "RX-7",
      "GLC",
      "Familia",
      "B2000",
      "B-Series",
      "929",
      "B2600",
      "MX-6",
      "MPV",
      "MX-5",
      "Navajo",
      "323",
      "Protege",
      "MX-3",
      "B-Series Plus",
      "Miata MX-5",
      "Millenia",
      "B2500",
      "Tribute",
      "Protege5",
      "Mazda6",
      "Mazda3",
      "RX-8",
      "Mazda6 5-Door",
      "Mazda5",
      "Mazda6 Sport",
      "Mazdaspeed6",
      "CX-7",
      "Mazdaspeed 3",
      "CX-9",
      "Mazda2",
      "CX-5"
    ]
  },
  {
    "manufacturer": "Mitsubishi",
    "model": [
      "Space",
      "Galant",
      "Mirage",
      "Starion",
      "Pajero",
      "Cordia",
      "Tredia",
      "Truck",
      "Chariot",
      "Mighty Max",
      "Precis",
      "Excel",
      "L300",
      "Sigma",
      "Eclipse",
      "GTO",
      "Diamante",
      "RVR",
      "3000GT",
      "Expo",
      "Mighty Max Macro",
      "Montero",
      "Expo LRV",
      "Challenger",
      "Montero Sport",
      "Lancer",
      "Lancer Evolution",
      "Outlander",
      "Endeavor",
      "Raider",
      "Tundra",
      "Outlander Sport",
      "i-MiEV"
    ]
  },
  {
    "manufacturer": "Subaru",
    "model": [
      "Brat",
      "XT",
      "Leone",
      "Justy",
      "Legacy",
      "Loyale",
      "Alcyone SVX",
      "SVX",
      "Impreza",
      "Forester",
      "Outback",
      "Outback Sport",
      "Baja",
      "Tribeca",
      "B9 Tribeca",
      "Impreza WRX",
      "BRZ"
    ]
  },
  {
    "manufacturer": "Lotus",
    "model": ["Esprit Turbo", "Esprit", "Elan", "Exige", "Elise", "Evora"]
  },
  {
    "manufacturer": "Lincoln",
    "model": [
      "Town Car",
      "Continental",
      "Mark VII",
      "Continental Mark VII",
      "Mark VIII",
      "Navigator",
      "LS",
      "Blackwood",
      "Aviator",
      "Zephyr",
      "Mark LT",
      "MKX",
      "MKZ",
      "Navigator L",
      "MKS",
      "MKT"
    ]
  },
  {
    "manufacturer": "Maserati",
    "model": [
      "Quattroporte",
      "Biturbo",
      "228",
      "430",
      "Spyder",
      "Karif",
      "Gran Sport",
      "Coupe",
      "GranSport",
      "GranTurismo"
    ]
  },
  {
    "manufacturer": "Saab",
    "model": ["900", "9000", "9-3", "9-5", "9-7X", "9-2X", "9-4X"]
  },
  {
    "manufacturer": "Audi",
    "model": [
      "5000S",
      "4000s",
      "Quattro",
      "Coupe GT",
      "5000CS Quattro",
      "4000s Quattro",
      "4000CS Quattro",
      "4000",
      "5000CS",
      "90",
      "80/90",
      "80",
      "100",
      "200",
      "V8",
      "Coupe Quattro",
      "S4",
      "Cabriolet",
      "riolet",
      "S6",
      "A6",
      "A4",
      "A8",
      "TT",
      "S8",
      "Allroad",
      "RS6",
      "RS 6",
      "A3",
      "Q7",
      "RS4",
      "RS 4",
      "S5",
      "R8",
      "A5",
      "Q5",
      "A7"
    ]
  },
  {
    "manufacturer": "Suzuki",
    "model": [
      "SJ 410",
      "Cultus",
      "SJ",
      "Swift",
      "Sidekick",
      "Samurai",
      "Esteem",
      "X-90",
      "Vitara",
      "Grand Vitara",
      "XL-7",
      "Aerio",
      "Daewoo Lacetti",
      "Daewoo Magnus",
      "Forenza",
      "Verona",
      "Reno",
      "XL7",
      "SX4",
      "Equator",
      "Kizashi"
    ]
  },
  {
    "manufacturer": "Lamborghini",
    "model": [
      "Countach",
      "Diablo",
      "Murciélago",
      "Gallardo",
      "Reventón",
      "Murciélago LP640",
      "Aventador"
    ]
  },
  {
    "manufacturer": "Merkur",
    "model": ["XR4Ti"]
  },
  {
    "manufacturer": "Land Rover",
    "model": [
      "Range Rover",
      "Sterling",
      "Defender",
      "Range Rover Classic",
      "Defender 110",
      "Discovery",
      "Defender 90",
      "Discovery Series II",
      "Freelander",
      "LR3",
      "Range Rover Sport",
      "LR2",
      "LR4",
      "Defender Ice Edition",
      "Range Rover Evoque"
    ]
  },
  {
    "manufacturer": "Acura",
    "model": [
      "Legend",
      "Integra",
      "NSX",
      "Vigor",
      "TL",
      "RL",
      "SLX",
      "CL",
      "MDX",
      "RSX",
      "TSX",
      "RDX",
      "ZDX"
    ]
  },
  {
    "manufacturer": "Lexus",
    "model": [
      "LS",
      "ES",
      "SC",
      "GS",
      "LX",
      "RX",
      "IS",
      "GX",
      "RX Hybrid",
      "IS-F",
      "IS F",
      "LS Hybrid",
      "HS",
      "CT",
      "LFA"
    ]
  },
  {
    "manufacturer": "Eagle",
    "model": ["Talon", "Premier", "Summit", "Vision"]
  },
  {
    "manufacturer": "Alfa Romeo",
    "model": ["164", "Spider"]
  },
  {
    "manufacturer": "Daihatsu",
    "model": ["Charade", "Rocky"]
  },
  {
    "manufacturer": "Geo",
    "model": ["Metro", "Prizm", "Storm", "Tracker"]
  },
  {
    "manufacturer": "GMC",
    "model": [
      "1500",
      "2500",
      "3500",
      "1500 Club Coupe",
      "2500 Club Coupe",
      "3500 Club Coupe",
      "Jimmy",
      "Rally Wagon 1500",
      "Rally Wagon 2500",
      "Rally Wagon 3500",
      "Safari",
      "Sonoma Club",
      "Sonoma",
      "Suburban 1500",
      "Suburban 2500",
      "Vandura 1500",
      "Vandura 2500",
      "Vandura 3500",
      "Yukon",
      "Sonoma Club Coupe",
      "Rally Wagon G2500",
      "Rally Wagon G3500",
      "Vandura G1500",
      "Vandura G2500",
      "Vandura G3500",
      "Savana 1500",
      "Savana 2500",
      "Savana 3500",
      "Envoy",
      "EV1",
      "Sierra 1500",
      "Sierra 2500",
      "Sierra 3500",
      "Yukon Denali",
      "Yukon XL 1500",
      "Yukon XL 2500",
      "Envoy XL",
      "Canyon",
      "Envoy XUV",
      "Sierra Denali",
      "Sierra 3500HD",
      "Sierra 2500HD",
      "Yukon XL",
      "Savana Cargo Van",
      "Sierra Hybrid",
      "Savana",
      "Acadia",
      "Sierra",
      "Terrain"
    ]
  },
  {
    "manufacturer": "Hyundai",
    "model": [
      "Elantra",
      "Excel",
      "Scoupe",
      "Sonata",
      "Accent",
      "Tiburon",
      "Santa Fe",
      "XG300",
      "XG350",
      "Tucson",
      "Azera",
      "Veracruz",
      "Entourage",
      "Genesis",
      "Genesis Coupe",
      "Equus",
      "HED-5",
      "Veloster"
    ]
  },
  {
    "manufacturer": "Infiniti",
    "model": [
      "G",
      "M",
      "Q",
      "J",
      "I",
      "QX",
      "G35",
      "FX",
      "QX56",
      "G37",
      "EX",
      "G25",
      "IPL G",
      "JX"
    ]
  },
  {
    "manufacturer": "Isuzu",
    "model": [
      "Amigo",
      "Impulse",
      "Rodeo",
      "Space",
      "Stylus",
      "Trooper",
      "Hombre",
      "Oasis",
      "Hombre Space",
      "VehiCROSS",
      "Rodeo Sport",
      "Axiom",
      "Ascender",
      "i-Series",
      "i-280",
      "i-350",
      "i-290",
      "i-370"
    ]
  },
  {
    "manufacturer": "Jaguar",
    "model": ["XJ Series", "XK Series", "S-Type", "X-Type", "XK", "XJ", "XF"]
  },
  {
    "manufacturer": "Jeep",
    "model": [
      "Cherokee",
      "Comanche",
      "Wrangler",
      "Grand Cherokee",
      "Liberty",
      "Commander",
      "Compass",
      "Patriot"
    ]
  },
  {
    "manufacturer": "Saturn",
    "model": [
      "S-Series",
      "L-Series",
      "VUE",
      "Ion",
      "Relay",
      "Outlook",
      "Aura",
      "Sky",
      "Astra"
    ]
  },
  {
    "manufacturer": "Volvo",
    "model": [
      "240",
      "740",
      "940",
      "960",
      "850",
      "S90",
      "V90",
      "C70",
      "S70",
      "V70",
      "S80",
      "S40",
      "V40",
      "S60",
      "XC90",
      "XC70",
      "V50",
      "C30",
      "XC60"
    ]
  },
  {
    "manufacturer": "HUMMER",
    "model": ["H1", "H2", "H2 SUT", "H2 SUV", "H3", "H3T"]
  },
  {
    "manufacturer": "Kia",
    "model": [
      "Sephia",
      "Sportage",
      "Mentor",
      "Spectra",
      "Rio",
      "Optima",
      "Sedona",
      "Sorento",
      "Amanti",
      "Spectra5",
      "Carens",
      "Rondo",
      "Rio5",
      "Mohave/Borrego",
      "Borrego",
      "Soul",
      "Forte"
    ]
  },
  {
    "manufacturer": "Holden",
    "model": ["VS Commodore", "Monaro"]
  },
  {
    "manufacturer": "Corbin",
    "model": ["Sparrow"]
  },
  {
    "manufacturer": "Daewoo",
    "model": ["Lanos", "Leganza", "Nubira"]
  },
  {
    "manufacturer": "MINI",
    "model": [
      "MINI",
      "Cooper",
      "Clubman",
      "Cooper Clubman",
      "Countryman",
      "Cooper Countryman"
    ]
  },
  {
    "manufacturer": "Maybach",
    "model": ["57", "62", "57S", "Landaulet"]
  },
  {
    "manufacturer": "Spyker",
    "model": [
      "C8 Spyder",
      "C8 Spyder Wide Body",
      "C8 Laviolette",
      "C8 Double 12 S"
    ]
  },
  {
    "manufacturer": "Scion",
    "model": ["xA", "xB", "tC", "xD", "iQ", "FR-S"]
  },
  {
    "manufacturer": "Spyker Cars",
    "model": ["C8"]
  },
  {
    "manufacturer": "Aston Martin",
    "model": [
      "DB9",
      "Vanquish S",
      "DB9 Volante",
      "V8 Vantage",
      "Vantage",
      "DBS",
      "Rapide",
      "V8 Vantage S",
      "V12 Vantage",
      "Virage"
    ]
  },
  {
    "manufacturer": "Bentley",
    "model": [
      "Arnage",
      "Continental",
      "Azure",
      "Continental GT",
      "Continental Flying Spur",
      "Continental GTC",
      "Brooklands",
      "Continental Super",
      "Azure T",
      "Mulsanne"
    ]
  },
  {
    "manufacturer": "Panoz",
    "model": ["Esperante"]
  },
  {
    "manufacturer": "Rolls-Royce",
    "model": ["Phantom", "Ghost"]
  },
  {
    "manufacturer": "Ferrari",
    "model": [
      "F430",
      "612 Scaglietti",
      "F430 Spider",
      "599 GTB Fiorano",
      "430 Scuderia",
      "California",
      "458 Italia",
      "FF"
    ]
  },
  {
    "manufacturer": "Morgan",
    "model": ["Aero 8"]
  },
  {
    "manufacturer": "Peugeot",
    "model": ["207"]
  },
  {
    "manufacturer": "Foose",
    "model": ["Hemisfear"]
  },
  {
    "manufacturer": "Aptera",
    "model": ["Typ-1", "2e", "Type-1h"]
  },
  {
    "manufacturer": "Smart",
    "model": ["Fortwo"]
  },
  {
    "manufacturer": "Bugatti",
    "model": ["Veyron"]
  },
  {
    "manufacturer": "Tesla",
    "model": ["Roadster", "Model S"]
  },
  {
    "manufacturer": "Ram",
    "model": ["1500", "2500", "3500", "Dakota", "C/V"]
  },
  {
    "manufacturer": "FIAT",
    "model": ["500", "Nuova 500"]
  },
  {
    "manufacturer": "McLaren",
    "model": ["MP4-12C"]
  },
  {
    "manufacturer": "Ford",
    "model": [
      "Model T",
      "Thunderbird",
      "E-Series",
      "Mustang",
      "Galaxie",
      "Fairlane",
      "Falcon",
      "Country",
      "Torino",
      "Bronco II",
      "Laser",
      "EXP",
      "Ranger",
      "Escort",
      "Tempo",
      "LTD",
      "F250",
      "F150",
      "E250",
      "LTD Crown Victoria",
      "Bronco",
      "E150",
      "F-Series",
      "Taurus",
      "Aerostar",
      "Courier",
      "Festiva",
      "Probe",
      "Explorer",
      "Crown Victoria",
      "Club Wagon",
      "Econoline E150",
      "Econoline E250",
      "Econoline E350",
      "F350",
      "Lightning",
      "Aspire",
      "Windstar",
      "Contour",
      "Expedition",
      "Th!nk",
      "Explorer Sport Trac",
      "Escape",
      "Excursion",
      "Explorer Sport",
      "Focus",
      "Fiesta",
      "ZX2",
      "Escort ZX2",
      "Freestar",
      "E350",
      "GT",
      "Freestyle",
      "Five Hundred",
      "F-250 Super Duty",
      "F-350 Super Duty",
      "E-350 Super Duty",
      "E-350 Super Duty Van",
      "Fusion",
      "F-Series Super Duty",
      "GT500",
      "Edge",
      "Expedition EL",
      "Taurus X",
      "F450",
      "Flex",
      "Transit Connect",
      "C-MAX Hybrid",
      "Focus ST"
    ]
  },
  {
    "manufacturer": "Chrysler",
    "model": [
      "Imperial",
      "Fifth Ave",
      "LeBaron",
      "New Yorker",
      "Town & Country",
      "Concorde",
      "LHS",
      "Cirrus",
      "Sebring",
      "300M",
      "300",
      "Grand Voyager",
      "Voyager",
      "PT Cruiser",
      "Prowler",
      "Crossfire",
      "Pacifica",
      "300C",
      "Crossfire Roadster",
      "Aspen",
      "200"
    ]
  },
  {
    "manufacturer": "Citroën",
    "model": ["2CV", "SM", "CX"]
  },
  {
    "manufacturer": "Hillman",
    "model": ["Minx Magnificent"]
  },
  {
    "manufacturer": "Chevrolet",
    "model": [
      "Corvette",
      "Corvair",
      "Corvair 500",
      "Camaro",
      "Bel Air",
      "Vega",
      "Monte Carlo",
      "Monza",
      "Caprice",
      "LUV",
      "Citation",
      "1500",
      "2500",
      "3500",
      "APV",
      "Astro",
      "Beretta",
      "Blazer",
      "Cavalier",
      "Corsica",
      "G-Series G10",
      "G-Series G20",
      "G-Series G30",
      "Lumina",
      "Lumina APV",
      "S10 Blazer",
      "S10",
      "Sportvan G10",
      "Sportvan G20",
      "Sportvan G30",
      "Suburban 1500",
      "Suburban 2500",
      "Caprice Classic",
      "Impala SS",
      "Impala",
      "K5 Blazer",
      "Tahoe",
      "Express 1500",
      "Express 2500",
      "Express 3500",
      "G-Series 1500",
      "G-Series 2500",
      "Malibu",
      "G-Series 3500",
      "Venture",
      "Metro",
      "Prizm",
      "Tracker",
      "Silverado",
      "Silverado 1500",
      "Silverado 2500",
      "Silverado 3500",
      "Avalanche",
      "Trailblazer",
      "Avalanche 1500",
      "Avalanche 2500",
      "SSR",
      "Aveo",
      "Classic",
      "Colorado",
      "Cobalt",
      "Equinox",
      "Uplander",
      "Suburban",
      "Silverado 3500HD",
      "HHR Panel",
      "Malibu Maxx",
      "HHR",
      "Silverado Hybrid",
      "Express",
      "Cobalt SS",
      "Traverse",
      "Volt",
      "Cruze",
      "Sonic"
    ]
  },
  {
    "manufacturer": "Cadillac",
    "model": [
      "Fleetwood",
      "Seville",
      "Allante",
      "Brougham",
      "DeVille",
      "Eldorado",
      "Sixty Special",
      "Catera",
      "Escalade",
      "Escalade EXT",
      "CTS",
      "Escalade ESV",
      "SRX",
      "XLR",
      "STS",
      "DTS",
      "XLR-V",
      "CTS-V",
      "STS-V"
    ]
  },
  {
    "manufacturer": "BMW",
    "model": [
      "600",
      "6 Series",
      "3 Series",
      "5 Series",
      "7 Series",
      "8 Series",
      "M5",
      "M3",
      "Z3",
      "X5",
      "M",
      "Z8",
      "525",
      "530",
      "745",
      "760",
      "Z4",
      "325",
      "545",
      "645",
      "X3",
      "330",
      "550",
      "650",
      "750",
      "M6",
      "M Roadster",
      "Z4 M",
      "Alpina B7",
      "1 Series",
      "X6",
      "Z4 M Roadster",
      "X5 M",
      "X6 M"
    ]
  },
  {
    "manufacturer": "Austin",
    "model": ["Mini", "Mini Cooper", "Mini Cooper S"]
  },
  {
    "manufacturer": "Fillmore",
    "model": ["Fillmore"]
  },
  {
    "manufacturer": "Fairthorpe",
    "model": ["Rockette"]
  },
  {
    "manufacturer": "Studebaker",
    "model": ["Avanti"]
  },
  {
    "manufacturer": "Pontiac",
    "model": [
      "Tempest",
      "Grand Prix",
      "GTO",
      "LeMans",
      "Bonneville",
      "Firebird",
      "6000",
      "Sunbird",
      "1000",
      "Parisienne",
      "Fiero",
      "Firefly",
      "Grand Am",
      "Safari",
      "Gemini",
      "Firebird Trans Am",
      "Chevette",
      "Turbo Firefly",
      "Trans Sport",
      "Grand Prix Turbo",
      "Firebird Formula",
      "Sunfire",
      "Montana",
      "Aztek",
      "Vibe",
      "G6",
      "Daewoo Kalos",
      "Monterey",
      "Montana SV6",
      "Torrent",
      "Solstice",
      "G5",
      "G8",
      "G3"
    ]
  },
  {
    "manufacturer": "Buick",
    "model": [
      "Special",
      "Riviera",
      "Electra",
      "Century",
      "Skyhawk",
      "Somerset",
      "LeSabre",
      "Regal",
      "Skylark",
      "Reatta",
      "Estate",
      "Coachbuilder",
      "Park Avenue",
      "Roadmaster",
      "Hearse",
      "Rendezvous",
      "Rainier",
      "LaCrosse",
      "Terraza",
      "Lucerne",
      "Enclave",
      "Verano"
    ]
  },
  {
    "manufacturer": "Rambler",
    "model": ["Classic"]
  },
  {
    "manufacturer": "Plymouth",
    "model": [
      "Fury",
      "Roadrunner",
      "Volare",
      "Horizon",
      "Reliant",
      "Voyager",
      "Laser",
      "Acclaim",
      "Colt",
      "Colt Vista",
      "Grand Voyager",
      "Sundance",
      "Neon",
      "Breeze",
      "Prowler"
    ]
  },
  {
    "manufacturer": "Volkswagen",
    "model": [
      "Beetle",
      "Golf",
      "Jetta",
      "Vanagon",
      "Scirocco",
      "Quantum",
      "GTI",
      "Cabriolet",
      "Passat",
      "Type 2",
      "Fox",
      "Corrado",
      "Eurovan",
      "riolet",
      "Golf III",
      "Jetta III",
      "rio",
      "New Beetle",
      "Touareg",
      "R32",
      "Phaeton",
      "Rabbit",
      "Eos",
      "GLI",
      "Touareg 2",
      "CC",
      "Tiguan",
      "Routan"
    ]
  },
  {
    "manufacturer": "Jensen",
    "model": ["Interceptor"]
  },
  {
    "manufacturer": "Oldsmobile",
    "model": [
      "Toronado",
      "88",
      "98",
      "Achieva",
      "Bravada",
      "Ciera",
      "Custom Cruiser",
      "Cutlass Supreme",
      "Silhouette",
      "Cutlass Cruiser",
      "Aurora",
      "Cutlass",
      "LSS",
      "Regency",
      "Intrigue",
      "Alero"
    ]
  },
  {
    "manufacturer": "Mercury",
    "model": [
      "Cougar",
      "Topaz",
      "Grand Marquis",
      "Lynx",
      "Capri",
      "Marquis",
      "Sable",
      "Tracer",
      "Villager",
      "Mystique",
      "Mountaineer",
      "Marauder",
      "Monterey",
      "Montego",
      "Mariner",
      "Milan"
    ]
  },
  {
    "manufacturer": "Shelby",
    "model": ["GT500", "GT350"]
  },
  {
    "manufacturer": "Dodge",
    "model": [
      "Charger",
      "Aspen",
      "Omni",
      "Aries",
      "Daytona",
      "Caravan",
      "Colt",
      "Viper",
      "D150 Club",
      "D150",
      "D250 Club",
      "D250",
      "D350 Club",
      "D350",
      "Dakota Club",
      "Dakota",
      "Dynasty",
      "Grand Caravan",
      "Monaco",
      "Ram 50",
      "Ram Van B150",
      "Ram Van B250",
      "Ram Van B350",
      "Ram Wagon B150",
      "Ram Wagon B250",
      "Ram Wagon B350",
      "Ramcharger",
      "Shadow",
      "Spirit",
      "Stealth",
      "Viper RT/10",
      "Intrepid",
      "Ram",
      "Ram 1500",
      "Ram 2500",
      "Ram 3500",
      "Avenger",
      "Neon",
      "Ram 1500 Club",
      "Ram 2500 Club",
      "Ram 3500 Club",
      "Ram Van 1500",
      "Ram Van 2500",
      "Ram Van 3500",
      "Stratus",
      "Durango",
      "Magnum",
      "Sprinter",
      "Nitro",
      "Caliber",
      "Challenger",
      "Journey"
    ]
  },
  {
    "manufacturer": "Porsche",
    "model": [
      "914",
      "944",
      "911",
      "928",
      "924 S",
      "924",
      "968",
      "Boxster",
      "Cayenne",
      "Carrera GT",
      "Cayman",
      "Panamera"
    ]
  },
  {
    "manufacturer": "Toyota",
    "model": [
      "Celica",
      "MR2",
      "Truck Xtracab SR5",
      "Previa",
      "Camry",
      "4Runner",
      "Corolla",
      "Cressida",
      "Land Cruiser",
      "Paseo",
      "Supra",
      "Tercel",
      "Xtra",
      "T100",
      "Avalon",
      "T100 Xtra",
      "Tacoma",
      "Tacoma Xtra",
      "RAV4",
      "Sienna",
      "Solara",
      "Tundra",
      "Ipsum",
      "Echo",
      "Highlander",
      "Prius",
      "Sequoia",
      "Matrix",
      "Yaris",
      "Camry Solara",
      "Highlander Hybrid",
      "Camry Hybrid",
      "FJ Cruiser",
      "TundraMax",
      "Venza",
      "Prius v",
      "Prius Plug-in Hybrid",
      "Prius c",
      "Prius Plug-in"
    ]
  },
  {
    "manufacturer": "Mercedes-Benz",
    "model": [
      "W123",
      "W126",
      "S-Class",
      "E-Class",
      "W201",
      "SL-Class",
      "190E",
      "300CE",
      "300D",
      "300E",
      "300SD",
      "300SE",
      "300SL",
      "300TE",
      "400E",
      "400SE",
      "500E",
      "500SEL",
      "500SL",
      "600SEL",
      "C-Class",
      "400SEL",
      "500SEC",
      "600SEC",
      "600SL",
      "SLK-Class",
      "M-Class",
      "CL-Class",
      "CLK-Class",
      "G-Class",
      "SLR McLaren",
      "CLS-Class",
      "G55 AMG",
      "SL65 AMG",
      "R-Class",
      "GL-Class",
      "SLK55 AMG",
      "CL65 AMG",
      "Sprinter",
      "GLK-Class",
      "SLS AMG",
      "SLS-Class",
      "Sprinter 2500",
      "Sprinter 3500"
    ]
  },
  {
    "manufacturer": "MG",
    "model": ["MGB"]
  },
  {
    "manufacturer": "Nissan",
    "model": [
      "280ZX",
      "Maxima",
      "Datsun/Nissan Z-car",
      "300ZX",
      "Sentra",
      "240SX",
      "NX",
      "Pathfinder",
      "Stanza",
      "Altima",
      "Quest",
      "200SX",
      "Frontier",
      "Xterra",
      "350Z",
      "Murano",
      "Titan",
      "Pathfinder Armada",
      "Armada",
      "350Z Roadster",
      "Versa",
      "Rogue",
      "Cube",
      "GT-R",
      "370Z",
      "Leaf",
      "JUKE",
      "NV1500",
      "NV2500",
      "NV3500"
    ]
  },
  {
    "manufacturer": "Honda",
    "model": [
      "Civic",
      "Accord",
      "CR-X",
      "Prelude",
      "del Sol",
      "Passport",
      "Odyssey",
      "CR-V",
      "Insight",
      "S2000",
      "Pilot",
      "Element",
      "Civic Si",
      "Civic GX",
      "Ridgeline",
      "Fit",
      "Accord Crosstour",
      "CR-Z",
      "FCX Clarity",
      "Crosstour"
    ]
  },
  {
    "manufacturer": "Renault",
    "model": ["Alliance"]
  },
  {
    "manufacturer": "Mazda",
    "model": [
      "626",
      "RX-7",
      "GLC",
      "Familia",
      "B2000",
      "B-Series",
      "929",
      "B2600",
      "MX-6",
      "MPV",
      "MX-5",
      "Navajo",
      "323",
      "Protege",
      "MX-3",
      "B-Series Plus",
      "Miata MX-5",
      "Millenia",
      "B2500",
      "Tribute",
      "Protege5",
      "Mazda6",
      "Mazda3",
      "RX-8",
      "Mazda6 5-Door",
      "Mazda5",
      "Mazda6 Sport",
      "Mazdaspeed6",
      "CX-7",
      "Mazdaspeed 3",
      "CX-9",
      "Mazda2",
      "CX-5"
    ]
  },
  {
    "manufacturer": "Mitsubishi",
    "model": [
      "Space",
      "Galant",
      "Mirage",
      "Starion",
      "Pajero",
      "Cordia",
      "Tredia",
      "Truck",
      "Chariot",
      "Mighty Max",
      "Precis",
      "Excel",
      "L300",
      "Sigma",
      "Eclipse",
      "GTO",
      "Diamante",
      "RVR",
      "3000GT",
      "Expo",
      "Mighty Max Macro",
      "Montero",
      "Expo LRV",
      "Challenger",
      "Montero Sport",
      "Lancer",
      "Lancer Evolution",
      "Outlander",
      "Endeavor",
      "Raider",
      "Tundra",
      "Outlander Sport",
      "i-MiEV"
    ]
  },
  {
    "manufacturer": "Subaru",
    "model": [
      "Brat",
      "XT",
      "Leone",
      "Justy",
      "Legacy",
      "Loyale",
      "Alcyone SVX",
      "SVX",
      "Impreza",
      "Forester",
      "Outback",
      "Outback Sport",
      "Baja",
      "Tribeca",
      "B9 Tribeca",
      "Impreza WRX",
      "BRZ"
    ]
  },
  {
    "manufacturer": "Lotus",
    "model": ["Esprit Turbo", "Esprit", "Elan", "Exige", "Elise", "Evora"]
  },
  {
    "manufacturer": "Lincoln",
    "model": [
      "Town Car",
      "Continental",
      "Mark VII",
      "Continental Mark VII",
      "Mark VIII",
      "Navigator",
      "LS",
      "Blackwood",
      "Aviator",
      "Zephyr",
      "Mark LT",
      "MKX",
      "MKZ",
      "Navigator L",
      "MKS",
      "MKT"
    ]
  },
  {
    "manufacturer": "Maserati",
    "model": [
      "Quattroporte",
      "Biturbo",
      "228",
      "430",
      "Spyder",
      "Karif",
      "Gran Sport",
      "Coupe",
      "GranSport",
      "GranTurismo"
    ]
  },
  {
    "manufacturer": "Saab",
    "model": ["900", "9000", "9-3", "9-5", "9-7X", "9-2X", "9-4X"]
  },
  {
    "manufacturer": "Audi",
    "model": [
      "5000S",
      "4000s",
      "Quattro",
      "Coupe GT",
      "5000CS Quattro",
      "4000s Quattro",
      "4000CS Quattro",
      "4000",
      "5000CS",
      "90",
      "80/90",
      "80",
      "100",
      "200",
      "V8",
      "Coupe Quattro",
      "S4",
      "Cabriolet",
      "riolet",
      "S6",
      "A6",
      "A4",
      "A8",
      "TT",
      "S8",
      "Allroad",
      "RS6",
      "RS 6",
      "A3",
      "Q7",
      "RS4",
      "RS 4",
      "S5",
      "R8",
      "A5",
      "Q5",
      "A7"
    ]
  },
  {
    "manufacturer": "Suzuki",
    "model": [
      "SJ 410",
      "Cultus",
      "SJ",
      "Swift",
      "Sidekick",
      "Samurai",
      "Esteem",
      "X-90",
      "Vitara",
      "Grand Vitara",
      "XL-7",
      "Aerio",
      "Daewoo Lacetti",
      "Daewoo Magnus",
      "Forenza",
      "Verona",
      "Reno",
      "XL7",
      "SX4",
      "Equator",
      "Kizashi"
    ]
  },
  {
    "manufacturer": "Lamborghini",
    "model": [
      "Countach",
      "Diablo",
      "Murciélago",
      "Gallardo",
      "Reventón",
      "Murciélago LP640",
      "Aventador"
    ]
  },
  {
    "manufacturer": "Merkur",
    "model": ["XR4Ti"]
  },
  {
    "manufacturer": "Land Rover",
    "model": [
      "Range Rover",
      "Sterling",
      "Defender",
      "Range Rover Classic",
      "Defender 110",
      "Discovery",
      "Defender 90",
      "Discovery Series II",
      "Freelander",
      "LR3",
      "Range Rover Sport",
      "LR2",
      "LR4",
      "Defender Ice Edition",
      "Range Rover Evoque"
    ]
  },
  {
    "manufacturer": "Acura",
    "model": [
      "Legend",
      "Integra",
      "NSX",
      "Vigor",
      "TL",
      "RL",
      "SLX",
      "CL",
      "MDX",
      "RSX",
      "TSX",
      "RDX",
      "ZDX"
    ]
  },
  {
    "manufacturer": "Lexus",
    "model": [
      "LS",
      "ES",
      "SC",
      "GS",
      "LX",
      "RX",
      "IS",
      "GX",
      "RX Hybrid",
      "IS-F",
      "IS F",
      "LS Hybrid",
      "HS",
      "CT",
      "LFA"
    ]
  },
  {
    "manufacturer": "Eagle",
    "model": ["Talon", "Premier", "Summit", "Vision"]
  },
  {
    "manufacturer": "Alfa Romeo",
    "model": ["164", "Spider"]
  },
  {
    "manufacturer": "Daihatsu",
    "model": ["Charade", "Rocky"]
  },
  {
    "manufacturer": "Geo",
    "model": ["Metro", "Prizm", "Storm", "Tracker"]
  },
  {
    "manufacturer": "GMC",
    "model": [
      "1500",
      "2500",
      "3500",
      "1500 Club Coupe",
      "2500 Club Coupe",
      "3500 Club Coupe",
      "Jimmy",
      "Rally Wagon 1500",
      "Rally Wagon 2500",
      "Rally Wagon 3500",
      "Safari",
      "Sonoma Club",
      "Sonoma",
      "Suburban 1500",
      "Suburban 2500",
      "Vandura 1500",
      "Vandura 2500",
      "Vandura 3500",
      "Yukon",
      "Sonoma Club Coupe",
      "Rally Wagon G2500",
      "Rally Wagon G3500",
      "Vandura G1500",
      "Vandura G2500",
      "Vandura G3500",
      "Savana 1500",
      "Savana 2500",
      "Savana 3500",
      "Envoy",
      "EV1",
      "Sierra 1500",
      "Sierra 2500",
      "Sierra 3500",
      "Yukon Denali",
      "Yukon XL 1500",
      "Yukon XL 2500",
      "Envoy XL",
      "Canyon",
      "Envoy XUV",
      "Sierra Denali",
      "Sierra 3500HD",
      "Sierra 2500HD",
      "Yukon XL",
      "Savana Cargo Van",
      "Sierra Hybrid",
      "Savana",
      "Acadia",
      "Sierra",
      "Terrain"
    ]
  },
  {
    "manufacturer": "Hyundai",
    "model": [
      "Elantra",
      "Excel",
      "Scoupe",
      "Sonata",
      "Accent",
      "Tiburon",
      "Santa Fe",
      "XG300",
      "XG350",
      "Tucson",
      "Azera",
      "Veracruz",
      "Entourage",
      "Genesis",
      "Genesis Coupe",
      "Equus",
      "HED-5",
      "Veloster"
    ]
  },
  {
    "manufacturer": "Infiniti",
    "model": [
      "G",
      "M",
      "Q",
      "J",
      "I",
      "QX",
      "G35",
      "FX",
      "QX56",
      "G37",
      "EX",
      "G25",
      "IPL G",
      "JX"
    ]
  },
  {
    "manufacturer": "Isuzu",
    "model": [
      "Amigo",
      "Impulse",
      "Rodeo",
      "Space",
      "Stylus",
      "Trooper",
      "Hombre",
      "Oasis",
      "Hombre Space",
      "VehiCROSS",
      "Rodeo Sport",
      "Axiom",
      "Ascender",
      "i-Series",
      "i-280",
      "i-350",
      "i-290",
      "i-370"
    ]
  },
  {
    "manufacturer": "Jaguar",
    "model": ["XJ Series", "XK Series", "S-Type", "X-Type", "XK", "XJ", "XF"]
  },
  {
    "manufacturer": "Jeep",
    "model": [
      "Cherokee",
      "Comanche",
      "Wrangler",
      "Grand Cherokee",
      "Liberty",
      "Commander",
      "Compass",
      "Patriot"
    ]
  },
  {
    "manufacturer": "Saturn",
    "model": [
      "S-Series",
      "L-Series",
      "VUE",
      "Ion",
      "Relay",
      "Outlook",
      "Aura",
      "Sky",
      "Astra"
    ]
  },
  {
    "manufacturer": "Volvo",
    "model": [
      "240",
      "740",
      "940",
      "960",
      "850",
      "S90",
      "V90",
      "C70",
      "S70",
      "V70",
      "S80",
      "S40",
      "V40",
      "S60",
      "XC90",
      "XC70",
      "V50",
      "C30",
      "XC60"
    ]
  },
  {
    "manufacturer": "HUMMER",
    "model": ["H1", "H2", "H2 SUT", "H2 SUV", "H3", "H3T"]
  },
  {
    "manufacturer": "Kia",
    "model": [
      "Sephia",
      "Sportage",
      "Mentor",
      "Spectra",
      "Rio",
      "Optima",
      "Sedona",
      "Sorento",
      "Amanti",
      "Spectra5",
      "Carens",
      "Rondo",
      "Rio5",
      "Mohave/Borrego",
      "Borrego",
      "Soul",
      "Forte"
    ]
  },
  {
    "manufacturer": "Holden",
    "model": ["VS Commodore", "Monaro"]
  },
  {
    "manufacturer": "Corbin",
    "model": ["Sparrow"]
  },
  {
    "manufacturer": "Daewoo",
    "model": ["Lanos", "Leganza", "Nubira"]
  },
  {
    "manufacturer": "MINI",
    "model": [
      "MINI",
      "Cooper",
      "Clubman",
      "Cooper Clubman",
      "Countryman",
      "Cooper Countryman"
    ]
  },
  {
    "manufacturer": "Maybach",
    "model": ["57", "62", "57S", "Landaulet"]
  },
  {
    "manufacturer": "Spyker",
    "model": [
      "C8 Spyder",
      "C8 Spyder Wide Body",
      "C8 Laviolette",
      "C8 Double 12 S"
    ]
  },
  {
    "manufacturer": "Scion",
    "model": ["xA", "xB", "tC", "xD", "iQ", "FR-S"]
  },
  {
    "manufacturer": "Spyker Cars",
    "model": ["C8"]
  },
  {
    "manufacturer": "Aston Martin",
    "model": [
      "DB9",
      "Vanquish S",
      "DB9 Volante",
      "V8 Vantage",
      "Vantage",
      "DBS",
      "Rapide",
      "V8 Vantage S",
      "V12 Vantage",
      "Virage"
    ]
  },
  {
    "manufacturer": "Bentley",
    "model": [
      "Arnage",
      "Continental",
      "Azure",
      "Continental GT",
      "Continental Flying Spur",
      "Continental GTC",
      "Brooklands",
      "Continental Super",
      "Azure T",
      "Mulsanne"
    ]
  },
  {
    "manufacturer": "Panoz",
    "model": ["Esperante"]
  },
  {
    "manufacturer": "Rolls-Royce",
    "model": ["Phantom", "Ghost"]
  },
  {
    "manufacturer": "Ferrari",
    "model": [
      "F430",
      "612 Scaglietti",
      "F430 Spider",
      "599 GTB Fiorano",
      "430 Scuderia",
      "California",
      "458 Italia",
      "FF"
    ]
  },
  {
    "manufacturer": "Morgan",
    "model": ["Aero 8"]
  },
  {
    "manufacturer": "Peugeot",
    "model": ["207"]
  },
  {
    "manufacturer": "Foose",
    "model": ["Hemisfear"]
  },
  {
    "manufacturer": "Aptera",
    "model": ["Typ-1", "2e", "Type-1h"]
  },
  {
    "manufacturer": "Smart",
    "model": ["Fortwo"]
  },
  {
    "manufacturer": "Bugatti",
    "model": ["Veyron"]
  },
  {
    "manufacturer": "Tesla",
    "model": ["Roadster", "Model S"]
  },
  {
    "manufacturer": "Ram",
    "model": ["1500", "2500", "3500", "Dakota", "C/V"]
  },
  {
    "manufacturer": "FIAT",
    "model": ["500", "Nuova 500"]
  },
  {
    "manufacturer": "McLaren",
    "model": ["MP4-12C"]
  }
]
    .map((item) => Manufacturer.fromJson(item))
    .takeWhile((value) => ids.add(value.manufacturer))
    .toList();
