name: user_repository
description: Dart package which manages the user domain.
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  parse_server_sdk: ^3.1.0
  uuid: ^3.0.0
